### PR TITLE
add send alive to client，case ddns useful

### PR DESCRIPTION
**Pull request by dongqiceo**

### CODE REVIEW

**Comment by dongqiceo** [comment]
better time ,I learn setting in website

**Comment by ryecoaaron** [comment]
This already exists.  Just check the persistent checkbox in the client config.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wireguard/blob/master/srv/salt/omv/deploy/wireguard/default.sls#L107

**Comment by dongqiceo** [comment]
> 这已经存在。只需选中客户端配置中的持久复选框即可。https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wireguard/blob/master/srv/salt/omv/deploy/wireguard/default.sls#L107

no,I mean not client, is server alive

**Comment by dongqiceo** [comment]
change by 125line,server config

**Comment by dongqiceo** [comment]
Before i was issue say that, Dynamic IP need Server keepalive

**Comment by ryecoaaron** [comment]
Just as client keepalive is an option, so should server side.  I will add it as an field on the tunnel form.

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wireguard/commit/ea987b7b6b2f6fb5aec3f7d93b2766fba13e048b

**Pull request closed without merging**
